export default {
  SET_PATIENT: 'SET_PATIENT',
  SET_PATIENT_INR: 'SET_PATIENT_INR',
  SET_PATIENT_CONTEXT: 'SET_PATIENT_CONTEXT',
  SET_PATIENT_CONTEXT_ENDED: 'SET_PATIENT_CONTEXT_ENDED',
  SET_TREATMENT_PLAN: 'SET_TREATMENT_PLAN',
  ADD_PLAN_TO_TREATMENT_PLAN: 'ADD_PLAN_TO_TREATMENT_PLAN',
  SET_SELECTED_PLAN: 'SET_SELECTED_PLAN',
  SET_TOKEN: 'SET_TOKEN',
  SET_SELECTED_OBSERVATION: 'SET_SELECTED_OBSERVATION',
  SET_OBSERVATIONS: 'SET_OBSERVATIONS'
}
