version: "3"
services:
   inr-ui:
      build:
        context: ./ui
        dockerfile: Dockerfile
      ports:
         - 80:80
      networks:
         - inr-network
      depends_on:
         - inr-middletier
   inr-middletier:
      build: 
        context: ./api/
        dockerfile: Dockerfile
      ports:
         - 8082:8082
      networks:
         - inr-network
      depends_on:
         - hapi-server
   hapi-server:
      build: 
        context: ./hapi-fhir/
        dockerfile: Dockerfile
      # might be good to not expose the HAPI server on production.
      ports:
         - 8080:8080
      volumes:
         - ./data:/var/lib/jetty/target
      networks:
         - inr-network

networks:
   inr-network:
      driver: bridge